### ISSUE TITLE
Setting the component file name to be imported from in index.ts file.

### ISSUE THREAD

**Issue by SimetrioKolev** [coolassassin/vs-rcci#1]
Hello and thank you for your awesome tool!!!
I just have one question though - what configuration I need to add in the `rcci.config.js` file in order to export as a variable for the templates the component file name?
Example:
If my component file name is `my-component.tsx` I need to use it in `index.ts` the following way: `import { #NAME# } from "./#FILE_NAME#"` where this should compile to `import { MyComponent } from "./my-component"`.

Thank you in advance!

**Comment by coolassassin** [comment]
Hello @SimetrioKolev!

Thank you for the question! It is really right question, because i forgot to support this case in my default templates.
Btw, i will help you.

First, you need to open `rcci.config.js` and add new placeholder like that:

```javascript
{
  ...
  placeholders: {
     ...
     COMPONENT_FILE_NAME: ({ filePrefix }) => filePrefix,
  }
}
```
After that, open your index file template and change it like this:
```javascript
export { #NAME# } from './#COMPONENT_FILE_NAME#';
```

And then - check, it shoud work.
You can see all available fields [here](https://github.com/coolassassin/reactcci#placeholders). I'm sure you can describe whatever you want by using them. But if you find the hard case i can update functionality to help you with.

Have a nice day! 😊

**Comment by SimetrioKolev** [comment]
Hey, brother, thank you for your quick response!
Unfortunately for some reason it doesn't work. Look what I got compiled on
creation:
import { MyComponent } from './#FILE_NAME#';
I have set  in the config file exactly what you've suggested:
FILE_NAME: ({ filePrefix }) => filePrefix,
Any idea why it might not work? THanks in advance!

Best regards,
Petar.

**Comment by coolassassin** [comment]
> 

First of all, check the version of reactcci package in yarn.lock or package-json.lock. It must be 1.8.0 or higher.

If version is ok, you can try to use my updated "reactcci" package version. After you request I have released new version of package with this placeholder. You can try to delete your config and templates, or make a new project, and then run "yarn rcci" (npx rcci) again to init reactcci. I have checked this. It works.

If it not help you, so, you can attach you config file, or make a project on github with this issue and i will help you.

P.S.: No replacement without errors looks like that placeholder in file and placeholder in config have different names. Try to check or copy it.

**Comment by SimetrioKolev** [comment]
I have updated it to v1.8.4 before I tested it but you are right about the
yarn.lock file, I have forgotten to delete it before the package update.
I will remove it before I install your package again and I will delete the
templates folder. THank you, mate!!! Will give you feedback right after I
do it :)

**Comment by coolassassin** [comment]
So, I will close issue. If you find any problems - create a new one.

**Comment by SimetrioKolev** [comment]
Hey, Dmitriy :)

It's working perfectly, thank you so much :)))))
I hit another issue, though. I have installed your lib in our project under
devDependencies. A colleague of mine installed the VS Code extension and
when trying to create a component the add-on pops up a modal with a
question does he want to install reactcci in the project.
Do you have any idea why this might occur when we already have it
installed? Thanks in advance!

Best regards,
Petar.

**Comment by coolassassin** [comment]
Hello, @SimetrioKolev!

This extension check package by searching `./node_modules/reactcci`
It is searching in the root folder.
If package installed not in the root of project, you can open this folder in VSCode to make it as a root.
But, you have the alternative way. The extension has a setting. This setting named like a "Root".
So, you can set up your own root relatively to you current root.

After both of this ways it should work fine.

Btw, I heard that new yarn has feature, where node_modules folder is hidden. So, if you use this feature and cuz of this you have this trouble, let me know. I will try to find a solution in my next releases.
If you have `.pnp.js` file in project - this is it. I should support this type of projects 🙃

As a hack, you can manually add empty folders like `node_modules/reactcci` and it will be work fine

**Comment by coolassassin** [comment]
Hello again, @SimetrioKolev!

I have made a new realese. 0.5.0 version.
Now it should work fine with berry version of yarn 👌

**Comment by SimetrioKolev** [comment]
Hey there, mate =]

THanks for the update! Btw I am using yarn (v1.x.x) workspaces and I didn't
think at all about the root issue and it makes a lot of sense!
The thing is I have multiple projects in which I wish to use your add-on
and the extension is accepting a single path. I will try to pass the paths
as strings in an array, and as a last resort if this doesn't work I will
install your package in the root of the workspace instead of in every
package. Then it should work :)
Thank you for all the effort!!! Your add-on is amazing!!!

**Comment by coolassassin** [comment]
Hello @SimetrioKolev

It is great that we figured it out.
So yeah. You have two ways, then.
First is to set multiple paths for `folderPath` param as array.
Second is to use multi-project mode.  This mode allows you to select project in CLI mode, and use Project name in your templates.
For example, you have projects with this structure:
- `Project1/src/components/`
- `Project2/frontend/src/`
- `Project3/modules/`

Then you can set `folderPath` like that:
`['src/components/', 'frontend/src/', 'modules/']`
Then set `multiProject` to `true`, and that is it. My CLI will find your projects automatically.

P.s.: Would be glad if you star [my project](https://github.com/coolassassin/reactcci) 😊

**Comment by SimetrioKolev** [comment]
AMAZING!!! I will try it out =]
